resources:
  repositories:
  - repository: templates
    type: github
    endpoint: simonnineteen90
    name: simonnineteen90/azure-pipeline-template

extends:
  template: docker-build-push.yaml@templates
  parameters:
    dockerRepo: 'simondunn/email-sender'