trigger:
  - none

resources:
  repositories:
  - repository: templates
    type: github
    endpoint: Simon Dunn
    name: simonnineteen90/azure-pipeline-template

extends:
  template: /docker-build-push.yaml
  parameters:
    dockerRepo: 'email-sender'