deployment:
  replicaCount: 1

containers:
  repository: simondunn/email-send
  tag: "1.0"
  pullPolicy: Always
  name: email-send
  containerPort: 3001

dataValueOne: one

service:
  name: email-send
  protocol: TCP
  port: 3001
  targetPort: 3001

env:
  connectionString: connectionString
  topicName: topicName
  subscriptionName: subscriptionName
  emailAddress: emailAddress
  emailPassword: emailPassword
  # update templates to use values from this file