deployment:
  replicaCount: 1

containers:
  repository: simondunn/email-send
  tag: "1.0"
  pullPolicy: Always
  name: email-send
  containerPort: 3001

dataValueOne: one

service:
  name: email-send
  protocol: TCP
  port: 3001
  targetPort: 3001

  # update templates to use values from this file